version: '3'
volumes:                           # ※ホストOSで永続化
    postgres_data:
        driver: 'local'
services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: 'postgres_db'
    environment:
      POSTGRES_PASSWORD: postgres  #スーパーユーザ(postgres)のパスワード
      POSTGRES_USER: kanazawa          #ユーザアカウント
      POSTGRES_PASSWORD: dockerkanazawa  #ユーザアカウントのパスワード
      POSTGRES_DB: world_news          #DB名
      TZ: 'Asia/Tokyo'
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data    # ※ホストOSで永続化
      - ./postgres/sql:/docker-entrypoint-initdb.d
    networks:
      - world-news-net
  uwsgi: # サービス名
    build:
      context: ./docker/python/api
      dockerfile: Dockerfile
    container_name: world_news_api # コンテナの名前
    volumes:
      - ./api:/var/www/ #現在のフォルダをコンテナにマウント
    tty: true  # コンテナを立ち上げた後、起動させたままにする(このオプションを付けないと起動しても、すぐ停止してしまう)
    networks:
      - world-news-net
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # nginxのログをホストOSの /tmp/nginx_log に出力する
      - /tmp/nginx_log:/var/log/nginx
    links:
      - uwsgi
    ports:
      - "80:80"
      #- "443:443"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - world-news-net  
  batch:
    build:
      context: ./docker/python/batch
      dockerfile: Dockerfile
    container_name: world_news_batch # コンテナの名前
    volumes:
      - ./batch:/batch
    tty: true  # コンテナを立ち上げた後、起動させたままにする(このオプションを付けないと起動しても、すぐ停止してしまう)
    networks:
      - world-news-net
networks:
  world-news-net:
    driver: bridge