version: '3'
volumes:                           # ※ホストOSで永続化
    postgres_data:
        driver: 'local'
services:
  batch:
    build: .
    volumes:
      - .:/batch
    ports:
      - "8081:8081"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - world-news-net  
networks:
  world-news-net:
    driver: bridge